/*
* generated by Xtext
*/
package org.xtext.example.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyDSLStandaloneSetup extends MyDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new MyDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

