/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDSLRuntimeModule extends org.xtext.example.mydsl.AbstractMyDSLRuntimeModule {
	// contributed by org.eclipse.xtext.generator.xbase.XbaseGeneratorFragment
	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return org.eclipse.xtext.xbase.compiler.JvmModelGenerator.class;
	}

}
